spring.application.name=movie-ticket-platform

# ===============================
# DATABASE CONFIG (MySQL)
# ===============================
spring.datasource.url=jdbc:mysql://localhost:3306/movietix?useSSL=false&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=password

# MySQL Driver
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# ===============================
# JPA / HIBERNATE
# ===============================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Important for MySQL
spring.jpa.database-platform=org.hibernate.dialect.MySQL8Dialect
